name: auto_orientation
description: Set the device orientation programmatically for iOS and Android
version: 1.0.5
author: Sebastian Faujour <sf@bytepark.de>
homepage: https://github.com/bytepark/auto_orientation

environment:
  sdk: any
  flutter: any

dependencies:
    flutter:
      sdk: flutter

dev_dependencies:
    flutter_test:
      sdk: flutter

flutter:
  plugin:
    androidPackage: de.bytepark.autoorientation
    pluginClass: AutoOrientationPlugin
